language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

script: 
  # Build and run
  - qmake
  - make
  - ./boost_xpressive_example3
  # Get code coverage
  - ./get_code_cov
  - codecov
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
